// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Fallout4;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Fallout4;

public static partial class ECO
{
    public static class Activator
    {
        private static FormLink<IActivatorGetter> Construct(uint id) => new FormLink<IActivatorGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IActivatorGetter> Dank_workbench_acti_WorkbenchUniversal => Construct(0x1efdd);
        public static FormLink<IActivatorGetter> Dank_workshop_acti_WorkbenchUniversal => Construct(0x278e7);
    }
}
