// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Fallout4;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Fallout4;

public static partial class ECO
{
    public static class Book
    {
        private static FormLink<IBookGetter> Construct(uint id) => new FormLink<IBookGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IBookGetter> Dank_PerkMag_LegendarySpecialist3_World => Construct(0x6c3c0);
        public static FormLink<IBookGetter> Dank_PerkMag_LegendarySpecialist4_World => Construct(0x6c3c1);
        public static FormLink<IBookGetter> Dank_PerkMag_LegendarySpecialist1_World => Construct(0x6c3c2);
        public static FormLink<IBookGetter> Dank_PerkMag_LegendarySpecialist2 => Construct(0xe4c);
        public static FormLink<IBookGetter> Dank_PerkMag_LegendarySpecialist3 => Construct(0xe4d);
        public static FormLink<IBookGetter> Dank_PerkMag_LegendarySpecialist4 => Construct(0xe4e);
        public static FormLink<IBookGetter> Dank_PerkMag_LegendarySpecialist1 => Construct(0xe4f);
        public static FormLink<IBookGetter> Dank_PerkMag_LegendarySpecialist2_World => Construct(0x6c3bf);
    }
}
