// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Fallout4;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Fallout4;

public static partial class ECO
{
    public static class Component
    {
        private static FormLink<IComponentGetter> Construct(uint id) => new FormLink<IComponentGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IComponentGetter> Dank_c_Legendary_Microchip => Construct(0x800);
    }
}
