// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Fallout4;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Fallout4;

public static partial class ECO
{
    public static class EffectShader
    {
        private static FormLink<IEffectShaderGetter> Construct(uint id) => new FormLink<IEffectShaderGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IEffectShaderGetter> Dank_Shader_Armor_THUD_Corpse => Construct(0x6c3e7);
        public static FormLink<IEffectShaderGetter> Dank_Shader_Armor_THUD_Foe => Construct(0x6c3e8);
        public static FormLink<IEffectShaderGetter> Dank_Shader_Armor_THUD_Friend => Construct(0x6c3e9);
    }
}
