// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Fallout4;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Fallout4;

public static partial class ECO
{
    public static class Furniture
    {
        private static FormLink<IFurnitureGetter> Construct(uint id) => new FormLink<IFurnitureGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IFurnitureGetter> Dank_workbench_furn_WorkbenchArmorMod => Construct(0x1efde);
        public static FormLink<IFurnitureGetter> Dank_workbench_furn_WorkbenchChem => Construct(0x1efdf);
        public static FormLink<IFurnitureGetter> Dank_workbench_furn_WorkbenchFood => Construct(0x1efe0);
        public static FormLink<IFurnitureGetter> Dank_workbench_furn_WorkbenchWeaponMod => Construct(0x1efe1);
        public static FormLink<IFurnitureGetter> Dank_workbench_furn_WorkbenchArmorCreate => Construct(0x1efe3);
        public static FormLink<IFurnitureGetter> Dank_workbench_furn_WorkbenchWeaponCreate => Construct(0x1efe4);
        public static FormLink<IFurnitureGetter> Dank_workbench_furn_WorkbenchJunk => Construct(0x1efe5);
        public static FormLink<IFurnitureGetter> Dank_workbench_furn_WorkbenchUtility => Construct(0x1efe6);
        public static FormLink<IFurnitureGetter> Dank_workbench_furn_WorkbenchAmmo => Construct(0x1efe7);
        public static FormLink<IFurnitureGetter> Dank_workbench_furn_WorkbenchPowerArmor => Construct(0x4a0c6);
    }
}
