// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Fallout4;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Fallout4;

public static partial class ECO
{
    public static class Global
    {
        private static FormLink<IGlobalGetter> Construct(uint id) => new FormLink<IGlobalGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IGlobalGetter> Dank_RecipeEnabled_FO76 => Construct(0x855);
        public static FormLink<IGlobalGetter> Dank_RecipeEnabled_Special_Armor => Construct(0x856);
        public static FormLink<IGlobalGetter> Dank_RecipeEnabled_Special_Gun => Construct(0x857);
        public static FormLink<IGlobalGetter> Dank_RecipeEnabled_Special_Melee => Construct(0x858);
        public static FormLink<IGlobalGetter> Dank_RecipeEnabled_Special => Construct(0x859);
        public static FormLink<IGlobalGetter> Dank_RecipeEnabled_Special_Legendary2 => Construct(0x85a);
        public static FormLink<IGlobalGetter> Dank_RecipeEnabled_Modifier_Damage => Construct(0x85b);
        public static FormLink<IGlobalGetter> Dank_RecipeEnabled_Modifier_Protection => Construct(0x85c);
        public static FormLink<IGlobalGetter> Dank_RecipeEnabled_Modifier_Ammo => Construct(0x85d);
        public static FormLink<IGlobalGetter> Dank_RecipeEnabled_Modifier_Firerate => Construct(0x85e);
        public static FormLink<IGlobalGetter> Dank_RecipeEnabled_Modifier_FireMode => Construct(0x861);
        public static FormLink<IGlobalGetter> Dank_RecipeEnabled_Modifier_Projectile => Construct(0x862);
        public static FormLink<IGlobalGetter> Dank_RecipeEnabled_Modifier_Recoil => Construct(0x863);
        public static FormLink<IGlobalGetter> Dank_RecipeEnabled_Enhance_Armor => Construct(0x865);
        public static FormLink<IGlobalGetter> Dank_RecipeEnabled_Enhance_Melee => Construct(0x866);
        public static FormLink<IGlobalGetter> Dank_RecipeEnabled_Custom => Construct(0x868);
        public static FormLink<IGlobalGetter> Dank_RecipeEnabled_Vanilla => Construct(0xcab);
        public static FormLink<IGlobalGetter> Dank_RecipeEnabled_Modifier_Jump => Construct(0xcf8);
        public static FormLink<IGlobalGetter> Dank_RecipeEnabled_Modifier_Zoom => Construct(0xcf9);
        public static FormLink<IGlobalGetter> Dank_ModScrapScalar_Microchips => Construct(0xd1a);
        public static FormLink<IGlobalGetter> Dank_InjectorUnlock_Legendary => Construct(0xd1b);
        public static FormLink<IGlobalGetter> Dank_RecipeEnabled_Special_PA => Construct(0xe43);
        public static FormLink<IGlobalGetter> Dank_QM_MenuToggle_G_Ammo => Construct(0xde46);
        public static FormLink<IGlobalGetter> Dank_QM_MenuToggle_G_Mode => Construct(0xde47);
        public static FormLink<IGlobalGetter> Dank_QM_MenuToggle_G_SightedTransition => Construct(0xde48);
        public static FormLink<IGlobalGetter> Dank_QM_MenuToggle_G_Zoom => Construct(0xde49);
        public static FormLink<IGlobalGetter> Dank_QM_MenuToggle_M_Enhancement => Construct(0xde4a);
        public static FormLink<IGlobalGetter> Dank_RecipeEnabled_UserLegendary => Construct(0x2342a);
        public static FormLink<IGlobalGetter> Dank_RecipeEnabled_Modifier_Weave => Construct(0x2787c);
        public static FormLink<IGlobalGetter> Dank_Workbench_PickUp_PA => Construct(0x2bd05);
        public static FormLink<IGlobalGetter> Dank_Workbench_PickUp_UW => Construct(0x2bd06);
        public static FormLink<IGlobalGetter> Dank_Workbench_PickUp_PA_Auto => Construct(0x38ea8);
        public static FormLink<IGlobalGetter> Dank_Workbench_ArmorCreate => Construct(0x38edc);
        public static FormLink<IGlobalGetter> Dank_Workbench_ArmorModify => Construct(0x38edd);
        public static FormLink<IGlobalGetter> Dank_Workbench_WeaponCreate => Construct(0x38ede);
        public static FormLink<IGlobalGetter> Dank_Workbench_WeaponModify => Construct(0x38edf);
        public static FormLink<IGlobalGetter> Dank_Workbench_Ammo => Construct(0x38ee0);
        public static FormLink<IGlobalGetter> Dank_Workbench_Chem => Construct(0x38ee1);
        public static FormLink<IGlobalGetter> Dank_Workbench_Junk => Construct(0x38ee2);
        public static FormLink<IGlobalGetter> Dank_Workbench_Utility => Construct(0x38ee3);
        public static FormLink<IGlobalGetter> Dank_Workbench_Cooking => Construct(0x38ee4);
        public static FormLink<IGlobalGetter> Dank_Workshop_Ammo => Construct(0x3d3c8);
        public static FormLink<IGlobalGetter> Dank_Workshop_ArmorCreate => Construct(0x3d3c9);
        public static FormLink<IGlobalGetter> Dank_Workshop_ArmorModify => Construct(0x3d3ca);
        public static FormLink<IGlobalGetter> Dank_Workshop_Chem => Construct(0x3d3cb);
        public static FormLink<IGlobalGetter> Dank_Workshop_Cooking => Construct(0x3d3cc);
        public static FormLink<IGlobalGetter> Dank_Workshop_Junk => Construct(0x3d3cd);
        public static FormLink<IGlobalGetter> Dank_Workshop_Utility => Construct(0x3d3ce);
        public static FormLink<IGlobalGetter> Dank_Workshop_WeaponCreate => Construct(0x3d3cf);
        public static FormLink<IGlobalGetter> Dank_Workshop_WeaponModify => Construct(0x3d3d0);
        public static FormLink<IGlobalGetter> Dank_RecipeEnabled_Modifier_Misc => Construct(0x41864);
        public static FormLink<IGlobalGetter> Dank_RecipeEnabled_Modifier_Misc_PA => Construct(0x41865);
        public static FormLink<IGlobalGetter> Dank_RecipeEnabled_Modifier_Material_PA => Construct(0x41866);
        public static FormLink<IGlobalGetter> Dank_Workbench_PickUp_UW_Auto => Construct(0x4a116);
        public static FormLink<IGlobalGetter> Dank_RecipeEnabled_Items_Ammo => Construct(0x5b257);
        public static FormLink<IGlobalGetter> Dank_RecipeEnabled_Items_Armor => Construct(0x5b258);
        public static FormLink<IGlobalGetter> Dank_RecipeEnabled_Items_Weapon => Construct(0x5b259);
        public static FormLink<IGlobalGetter> Dank_Workbench_UnrestrictedPA => Construct(0x63b18);
        public static FormLink<IGlobalGetter> Dank_RecipeEnabled_Modifier_Accuracy => Construct(0x7d4b8);
        public static FormLink<IGlobalGetter> Dank_RecipeEnabled_Modifier_Range => Construct(0x7d4b9);
        public static FormLink<IGlobalGetter> Dank_RecipeEnabled_Modifier_Reload => Construct(0x8a1ec);
        public static FormLink<IGlobalGetter> Dank_RecipeEnabled_Modifier_HitBehavior => Construct(0x8e77e);
        public static FormLink<IGlobalGetter> Dank_QM_MenuToggle_HitBehavior => Construct(0x92bd0);
        public static FormLink<IGlobalGetter> Dank_RecipeSwitch_ChemUtility => Construct(0xac490);
        public static FormLink<IGlobalGetter> Dank_RecipeEnabled_Modifier_SightTrans => Construct(0xac49a);
        public static FormLink<IGlobalGetter> Dank_RecipeSwitch_ChemWeapon => Construct(0xac60c);
        public static FormLink<IGlobalGetter> Dank_RecipeEnabled_Items_Chems => Construct(0xb9196);
        public static FormLink<IGlobalGetter> Dank_RecipeEnabled_Items_Alcohol => Construct(0xb9197);
        public static FormLink<IGlobalGetter> Dank_RecipeEnabled_Items_Soda => Construct(0xb9198);
        public static FormLink<IGlobalGetter> Dank_Armor_Enhance_NightVisionEnabled => Construct(0xb9332);
        public static FormLink<IGlobalGetter> Dank_QM_MenuToggle_TacticalReload => Construct(0xc1bd5);
        public static FormLink<IGlobalGetter> Dank_QM_MenuToggle_Damage => Construct(0xc1bda);
        public static FormLink<IGlobalGetter> Dank_QM_MenuToggle_G_FireRate => Construct(0xc1bdb);
        public static FormLink<IGlobalGetter> Dank_RecipeEnabled_NoLegendary => Construct(0xc5e8a);
        public static FormLink<IGlobalGetter> Dank_RecipeEnabled_Scrap => Construct(0xc5e8b);
        public static FormLink<IGlobalGetter> Dank_RecipeEnabled_Armor_Size => Construct(0xc603d);
        public static FormLink<IGlobalGetter> Dank_RecipeEnabled_Armor_WeaveExtra => Construct(0xc603e);
    }
}
