// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Fallout4;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Fallout4;

public static partial class ECO
{
    public static class Ingestible
    {
        private static FormLink<IIngestibleGetter> Construct(uint id) => new FormLink<IIngestibleGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IIngestibleGetter> Dank_QGM_FavouriteItem => Construct(0xada);
        public static FormLink<IIngestibleGetter> Dank_QGM_FavouriteItem_FiringModeSwitch => Construct(0x81a25);
        public static FormLink<IIngestibleGetter> Dank_FavouriteItem_DropUniversalBench => Construct(0xa3be1);
        public static FormLink<IIngestibleGetter> Dank_FavouriteItem_DropPABench => Construct(0xac486);
    }
}
