// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Fallout4;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Fallout4;

public static partial class ECO
{
    public static class MagicEffect
    {
        private static FormLink<IMagicEffectGetter> Construct(uint id) => new FormLink<IMagicEffectGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IMagicEffectGetter> Dank_Effect_Legendary_Armor_UnlimitedAP => Construct(0x869);
        public static FormLink<IMagicEffectGetter> Dank_Effect_Legendary_FO76_Armor_Sneak => Construct(0x889);
        public static FormLink<IMagicEffectGetter> Dank_Effect_Armor_Enhance_Hack => Construct(0xacf);
        public static FormLink<IMagicEffectGetter> Dank_QGM_mgef_FavouriteItem => Construct(0xad9);
        public static FormLink<IMagicEffectGetter> Dank_Effect_Legendary_Weapon_Both_Crit => Construct(0xaed);
        public static FormLink<IMagicEffectGetter> Dank_Effect_Legendary_Armor_Hermit => Construct(0xb1e);
        public static FormLink<IMagicEffectGetter> Dank_Effect_Legendary_FO76_Weapon_Both_Suppressor_Target => Construct(0xc23);
        public static FormLink<IMagicEffectGetter> Dank_Effect_Legendary_FO76_Weapon_Melee_OnBlock_DamageRadiation => Construct(0xc2a);
        public static FormLink<IMagicEffectGetter> Dank_Effect_Legendary_FO76_Weapon_Melee_BlockRadiation => Construct(0xc2c);
        public static FormLink<IMagicEffectGetter> Dank_Effect_Legendary_FO76_Weapon_Melee_Protective => Construct(0xc2e);
        public static FormLink<IMagicEffectGetter> Dank_Effect_Legendary_FO76_Weapon_Melee_BlockFrenzies => Construct(0xc2f);
        public static FormLink<IMagicEffectGetter> Dank_Effect_Legendary_FO76_Weapon_Both_Suppressor => Construct(0xc31);
        public static FormLink<IMagicEffectGetter> Dank_Effect_Armor_JumpHeightModifier => Construct(0xe44);
        public static FormLink<IMagicEffectGetter> Dank_Effect_Legendary_FO76_Weapon_Gun_Bashing => Construct(0x1183);
        public static FormLink<IMagicEffectGetter> Dank_Effect_Legendary_FO76_Weapon_Melee_Overpowering => Construct(0x1184);
        public static FormLink<IMagicEffectGetter> Dank_Effect_Legendary_FO76_Weapon_Both_Executioner => Construct(0x1185);
        public static FormLink<IMagicEffectGetter> Dank_Effect_Legendary_Armor_FusionCoreCapacity => Construct(0x3d3a7);
        public static FormLink<IMagicEffectGetter> Dank_Effect_Armor_THUD_Corpse => Construct(0x6c3cf);
        public static FormLink<IMagicEffectGetter> Dank_Effect_Armor_THUD_Foe => Construct(0x6c3d0);
        public static FormLink<IMagicEffectGetter> Dank_Effect_Armor_THUD_Friend => Construct(0x6c3d1);
        public static FormLink<IMagicEffectGetter> Dank_Effect_Armor_THUD_Corpse_Shader => Construct(0x6c3e4);
        public static FormLink<IMagicEffectGetter> Dank_Effect_Armor_THUD_Foe_Shader => Construct(0x6c3e5);
        public static FormLink<IMagicEffectGetter> Dank_Effect_Armor_THUD_Friend_Shader => Construct(0x6c3e6);
        public static FormLink<IMagicEffectGetter> Dank_QGM_mgef_FavouriteItem_FiringModeSwitch => Construct(0x81a24);
        public static FormLink<IMagicEffectGetter> Dank_Effect_UniBench_DropItem => Construct(0xa3be3);
        public static FormLink<IMagicEffectGetter> Dank_Effect_PABench_DropItem => Construct(0xac488);
        public static FormLink<IMagicEffectGetter> Dank_Effect_Armor_Enhance_NightVision => Construct(0xb932a);
        public static FormLink<IMagicEffectGetter> Dank_Effect_Legendary_FO76_Weapon_Both_VampireRegenEffect => Construct(0xced60);
    }
}
