// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Fallout4;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Fallout4;

public static partial class ECO
{
    public static class MaterialSwap
    {
        private static FormLink<IMaterialSwapGetter> Construct(uint id) => new FormLink<IMaterialSwapGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IMaterialSwapGetter> Dank_ModernMechanix04 => Construct(0xf47);
        public static FormLink<IMaterialSwapGetter> Dank_ModernMechanix01 => Construct(0xf48);
        public static FormLink<IMaterialSwapGetter> Dank_Armor_Appearance_Invisible => Construct(0x9f8fa);
        public static FormLink<IMaterialSwapGetter> Dank_ModernMechanix02 => Construct(0xf45);
        public static FormLink<IMaterialSwapGetter> Dank_ModernMechanix03 => Construct(0xf46);
    }
}
