// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Fallout4;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Fallout4;

public static partial class ECO
{
    public static class ObjectEffect
    {
        private static FormLink<IObjectEffectGetter> Construct(uint id) => new FormLink<IObjectEffectGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IObjectEffectGetter> Dank_Ench_Legendary_Armor_UnlimitedAP => Construct(0x8ad);
        public static FormLink<IObjectEffectGetter> Dank_Ench_Legendary_FO76_Armor_Sneak => Construct(0x8be);
        public static FormLink<IObjectEffectGetter> Dank_Ench_Armor_Enhance_Hack => Construct(0xad0);
        public static FormLink<IObjectEffectGetter> Dank_Ench_Legendary_Weapon_Both_Crit => Construct(0xaef);
        public static FormLink<IObjectEffectGetter> Dank_Ench_Legendary_Armor_Hermit => Construct(0xb1f);
        public static FormLink<IObjectEffectGetter> Dank_Ench_Legendary_Armor_WaterBreathing => Construct(0xbd2);
        public static FormLink<IObjectEffectGetter> Dank_Ench_Legendary_FO76_Armor_Nocturnal => Construct(0xc33);
        public static FormLink<IObjectEffectGetter> Dank_Ench_Legendary_FO76_Armor_Regenerating => Construct(0xc35);
        public static FormLink<IObjectEffectGetter> Dank_Ench_Legendary_FO76_Armor_Vanguard => Construct(0xc36);
        public static FormLink<IObjectEffectGetter> Dank_Ench_Legendary_FO76_Weapon_Both_Suppressor => Construct(0xc38);
        public static FormLink<IObjectEffectGetter> Dank_Ench_Legendary_FO76_Weapon_Melee_Protective => Construct(0xc3a);
        public static FormLink<IObjectEffectGetter> Dank_Ench_Legendary_FO76_Weapon_Melee_BlockFrenzies => Construct(0xc3b);
        public static FormLink<IObjectEffectGetter> Dank_Ench_Legendary_FO76_Weapon_Melee_BlockIrradiates => Construct(0xc3c);
        public static FormLink<IObjectEffectGetter> Dank_Ench_Legendary_FO76_Weapon_Melee_BlockReflect => Construct(0xc3d);
        public static FormLink<IObjectEffectGetter> Dank_Ench_Armor_JumpHeight25 => Construct(0xe45);
        public static FormLink<IObjectEffectGetter> Dank_Ench_Armor_JumpHeight50 => Construct(0xe46);
        public static FormLink<IObjectEffectGetter> Dank_Ench_Armor_JumpHeight75 => Construct(0xe47);
        public static FormLink<IObjectEffectGetter> Dank_Ench_Armor_JumpHeight100 => Construct(0xe48);
        public static FormLink<IObjectEffectGetter> Dank_EnchPA_Endurance => Construct(0xe4a);
        public static FormLink<IObjectEffectGetter> Dank_EnchPA_Luck => Construct(0xe4b);
        public static FormLink<IObjectEffectGetter> Dank_Ench_Legendary_FO76_Weapon_Gun_Bashing => Construct(0x1186);
        public static FormLink<IObjectEffectGetter> Dank_Ench_Legendary_FO76_Weapon_Melee_Overpowering => Construct(0x1187);
        public static FormLink<IObjectEffectGetter> Dank_Ench_Legendary_FO76_Weapon_Both_Executioner => Construct(0x1188);
        public static FormLink<IObjectEffectGetter> Dank_Ench_Legendary_Armor_FusionCoreCapacity => Construct(0x3d3a8);
        public static FormLink<IObjectEffectGetter> Dank_Ench_Armor_THUD_Corpse => Construct(0x6c3cc);
        public static FormLink<IObjectEffectGetter> Dank_Ench_Armor_THUD_Friend => Construct(0x6c3cd);
        public static FormLink<IObjectEffectGetter> Dank_Ench_Armor_THUD_Foe => Construct(0x6c3ce);
        public static FormLink<IObjectEffectGetter> Dank_EnchPA_Agility => Construct(0x8a1df);
        public static FormLink<IObjectEffectGetter> Dank_EnchPA_Charisma => Construct(0x8a1e0);
        public static FormLink<IObjectEffectGetter> Dank_EnchPA_Strength => Construct(0x8a1e1);
        public static FormLink<IObjectEffectGetter> Dank_EnchPA_Perception => Construct(0x8a1e2);
        public static FormLink<IObjectEffectGetter> Dank_EnchPA_Intelligence => Construct(0x8a1e3);
        public static FormLink<IObjectEffectGetter> Dank_EnchPA_Nuka_Legendary => Construct(0x8a1e4);
        public static FormLink<IObjectEffectGetter> Dank_EnchPA_Quantum_Legendary => Construct(0x8a1e5);
        public static FormLink<IObjectEffectGetter> Dank_Ench_Armor_Enhance_NightVision => Construct(0xb932b);
        public static FormLink<IObjectEffectGetter> Dank_Ench_Legendary_FO76_Weapon_Both_Vampire => Construct(0xced5b);
        public static FormLink<IObjectEffectGetter> Dank_Ench_Armor_JumpHeight200 => Construct(0xced6a);
        public static FormLink<IObjectEffectGetter> Dank_Ench_Armor_JumpHeight300 => Construct(0xced6b);
        public static FormLink<IObjectEffectGetter> Dank_Ench_Armor_JumpHeight400 => Construct(0xced6c);
        public static FormLink<IObjectEffectGetter> Dank_Ench_Armor_JumpHeight500 => Construct(0xced6d);
    }
}
