// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Fallout4;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Fallout4;

public static partial class ECO
{
    public static class Perk
    {
        private static FormLink<IPerkGetter> Construct(uint id) => new FormLink<IPerkGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IPerkGetter> Dank_Perk_Armor_Enhance_Hack => Construct(0xace);
        public static FormLink<IPerkGetter> Dank_Perk_Legendary_Weapon_Both_Crit => Construct(0xaec);
        public static FormLink<IPerkGetter> Dank_Perk_Legendary_Armor_Hermit => Construct(0xb1a);
        public static FormLink<IPerkGetter> Dank_Perk_Legendary_FO76_Weapon_Melee_Protective => Construct(0xc20);
        public static FormLink<IPerkGetter> Dank_Perk_Legendary_FO76_Weapon_Both_Suppressor_Target => Construct(0xc22);
        public static FormLink<IPerkGetter> Dank_Perk_Legendary_FO76_Weapon_Both_Suppressor => Construct(0xc25);
        public static FormLink<IPerkGetter> Dank_Perk_Magazine_LegendarySpecialist => Construct(0xe88);
        public static FormLink<IPerkGetter> Dank_Perk_Magazine_LegendarySpecialist2 => Construct(0xe89);
        public static FormLink<IPerkGetter> Dank_Perk_Magazine_LegendarySpecialist3 => Construct(0xe8a);
        public static FormLink<IPerkGetter> Dank_Perk_Magazine_LegendarySpecialist4 => Construct(0xe8b);
        public static FormLink<IPerkGetter> Dank_Perk_Legendary_FO76_Weapon_Gun_Bashing => Construct(0x119a);
        public static FormLink<IPerkGetter> Dank_Perk_Legendary_FO76_Weapon_Melee_Overpowering => Construct(0x119b);
        public static FormLink<IPerkGetter> Dank_Perk_Legendary_FO76_Weapon_Both_Executioner => Construct(0x119c);
        public static FormLink<IPerkGetter> Dank_Perk_Workbench_PA => Construct(0x2bd02);
        public static FormLink<IPerkGetter> Dank_Perk_Workbench_UW => Construct(0x345ae);
        public static FormLink<IPerkGetter> Dank_Perk_Legendary_Armor_FusionCoreCapacity => Construct(0x3d3a5);
        public static FormLink<IPerkGetter> Dank_Perk_Armor_Enhance_NightVision => Construct(0xb9329);
        public static FormLink<IPerkGetter> Dank_Perk_Legendary_FO76_Armor_Sneak => Construct(0x9a4);
    }
}
