// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Fallout4;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Fallout4;

public static partial class ECO
{
    public static class Projectile
    {
        private static FormLink<IProjectileGetter> Construct(uint id) => new FormLink<IProjectileGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IProjectileGetter> Dank_AlienBlasterProjectileRed_Fast => Construct(0x953);
        public static FormLink<IProjectileGetter> Dank_AlienBlasterProjectileRed_Fastest => Construct(0x954);
        public static FormLink<IProjectileGetter> Dank_AlienBlasterProjectileGreen_Fastest => Construct(0x955);
        public static FormLink<IProjectileGetter> Dank_AlienBlasterProjectileGreen_Fast => Construct(0x956);
        public static FormLink<IProjectileGetter> Dank_AlienBlasterProjectile_Faster => Construct(0xb38);
        public static FormLink<IProjectileGetter> Dank_AlienBlasterProjectile_Fastest => Construct(0xb39);
        public static FormLink<IProjectileGetter> Dank_PlasmaProjectileRedLarge => Construct(0x94b);
        public static FormLink<IProjectileGetter> Dank_PlasmaProjectileRedSmall => Construct(0x94c);
        public static FormLink<IProjectileGetter> Dank_PlasmaProjectileRedSmallFast => Construct(0x94d);
        public static FormLink<IProjectileGetter> Dank_PlasmaProjectileBlueLarge => Construct(0x94e);
        public static FormLink<IProjectileGetter> Dank_PlasmaProjectileBlueSmallFast => Construct(0x94f);
        public static FormLink<IProjectileGetter> Dank_PlasmaProjectileBlueSmall => Construct(0x950);
        public static FormLink<IProjectileGetter> Dank_AlienBlasterProjectileGreen => Construct(0x951);
        public static FormLink<IProjectileGetter> Dank_AlienBlasterProjectileRed => Construct(0x952);
    }
}
