// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Fallout4;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Fallout4;

public static partial class ECO
{
    public static class Spell
    {
        private static FormLink<ISpellGetter> Construct(uint id) => new FormLink<ISpellGetter>(ModKey.MakeFormKey(id));
        public static FormLink<ISpellGetter> Dank_ab_Perk_Hermit_CarryWeight => Construct(0xb1b);
        public static FormLink<ISpellGetter> Dank_ab_Perk_Hermit_ActionPoints => Construct(0xb1c);
        public static FormLink<ISpellGetter> Dank_ab_Perk_Legendary_FO76_Weapon_Both_Suppressor_Target => Construct(0xc24);
        public static FormLink<ISpellGetter> Dank_ab_Legendary_FO76_Weapon_Melee_OnBlock_Frenzy => Construct(0xc29);
        public static FormLink<ISpellGetter> Dank_ab_Legendary_FO76_Weapon_Melee_OnBlock_DamageRadiation => Construct(0xc2b);
        public static FormLink<ISpellGetter> Dank_ab_Perk_Legendary_FusionCoreDamageRate => Construct(0x3d3a6);
        public static FormLink<ISpellGetter> Dank_ab_Armor_THUD_Corpse => Construct(0x6c3e1);
        public static FormLink<ISpellGetter> Dank_ab_Armor_THUD_Foe => Construct(0x6c3e2);
        public static FormLink<ISpellGetter> Dank_ab_Armor_THUD_Friend => Construct(0x6c3e3);
        public static FormLink<ISpellGetter> Dank_ab_Armor_Enhance_NightVision => Construct(0xb9328);
    }
}
