// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Fallout4;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Fallout4;

public static partial class ECO
{
    public static class Static
    {
        private static FormLink<IStaticGetter> Construct(uint id) => new FormLink<IStaticGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IStaticGetter> ModernMechanixHighPoly01 => Construct(0x6c3c3);
        public static FormLink<IStaticGetter> ModernMechanixHighPoly02 => Construct(0x6c3c4);
        public static FormLink<IStaticGetter> ModernMechanixHighPoly03 => Construct(0x6c3c5);
        public static FormLink<IStaticGetter> ModernMechanixHighPoly04 => Construct(0x6c3c6);
    }
}
