// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Fallout4;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Fallout4;

public static partial class ECO
{
    public static class Terminal
    {
        private static FormLink<ITerminalGetter> Construct(uint id) => new FormLink<ITerminalGetter>(ModKey.MakeFormKey(id));
        public static FormLink<ITerminalGetter> Dank_Config => Construct(0x958);
        public static FormLink<ITerminalGetter> Dank_Config_RecipeLegendary => Construct(0x959);
        public static FormLink<ITerminalGetter> Dank_Config_Slots => Construct(0x99d);
        public static FormLink<ITerminalGetter> Dank_Config_Slots_Weapon => Construct(0x9a1);
        public static FormLink<ITerminalGetter> Dank_Config_Cheat => Construct(0x9a2);
        public static FormLink<ITerminalGetter> Dank_Config_Slots_Armor => Construct(0xe7c);
        public static FormLink<ITerminalGetter> Dank_Config_ScrapScalar => Construct(0xe7d);
        public static FormLink<ITerminalGetter> Dank_Config_LegendaryInject => Construct(0xe7e);
        public static FormLink<ITerminalGetter> Dank_Config_LegendaryInject_Readme => Construct(0xe7f);
        public static FormLink<ITerminalGetter> Dank_Config_RecipeAttach => Construct(0x5164);
        public static FormLink<ITerminalGetter> Dank_Config_QuickMod => Construct(0x1efcb);
        public static FormLink<ITerminalGetter> Dank_Config_Bench_PickUp => Construct(0x38ea7);
        public static FormLink<ITerminalGetter> Dank_Config_Bench => Construct(0x3d3d1);
        public static FormLink<ITerminalGetter> Dank_Config_Bench_Mobile => Construct(0x3d3d2);
        public static FormLink<ITerminalGetter> Dank_Config_Bench_Workshop => Construct(0x3d3d3);
        public static FormLink<ITerminalGetter> Dank_Config_RecipeItem => Construct(0xb9195);
    }
}
