// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Fallout4;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Fallout4;

public static partial class ECO
{
    public static class Transform
    {
        private static FormLink<ITransformGetter> Construct(uint id) => new FormLink<ITransformGetter>(ModKey.MakeFormKey(id));
        public static FormLink<ITransformGetter> Dank_workbench_trns_WorkbenchPA => Construct(0x4a0c4);
        public static FormLink<ITransformGetter> Dank_workbench_trns_WorkbenchUniversal => Construct(0x1efdc);
    }
}
